### PR TITLE
Add additional scaffolding for release, docs and examples

### PR DESCRIPTION
**Pull request by prologic**

### CODE REVIEW

**Comment by prologic** [comment]
Just following the docs [here](https://www.terraform.io/docs/registry/providers/publishing.html) and [here](https://www.terraform.io/docs/registry/providers/docs.html)

**Comment by alexperezau** [comment]
> Just following the docs [here](https://www.terraform.io/docs/registry/providers/publishing.html) and [here](https://www.terraform.io/docs/registry/providers/docs.html)

**Review by alexperezau — COMMENTED** [review]
Look solid for an initial release. Documentation follows the standards expected by Hashicorp.

**Review by alexperezau — APPROVED** [review]
Approved.

**Pull request merged**
